[package]
name = "hyena-api"
version = "0.1.0"
authors = ["Tomasz Barański <tomasz.baranski@collective-sense.com>"]

[dependencies]
bincode = "0.8.0"
log = "0.3.8"
serde = "1.0.9"
serde_derive = "1.0.9"

[dependencies.hyena-engine]
path = "../hyena-engine"
