[package]
name = "hyena-bloom-filter"
version = "0.1.0"
authors = ["Jacek Całusiński <forger@forger.pl>"]
edition = "2018"

[dependencies]
fnv = "1.0.6"
fxhash = "0.2.1"
serde = "1.0.61"
serde_derive = "1.0.61"

[features]
default = []
nightly = []
